import subprocess


def test_alembic_upgrade_head_runs():
    """`alembic upgrade head` must apply cleanly against DATABASE_URL.

    This is a real DDL run (not mocked): it verifies the autogenerated
    migration's imports (CITEXT, ARRAY) and statements are correct against
    an actual Postgres instance.
    """
    result = subprocess.run(
        ["poetry", "run", "alembic", "upgrade", "head"],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
