import subprocess

from sqlalchemy import inspect
from sqlalchemy.engine import Engine


def test_alembic_upgrade_head_runs():
    """`alembic upgrade head` must apply cleanly against DATABASE_URL.

    This is a real DDL run (not mocked): it verifies the autogenerated
    migration's imports (CITEXT, ARRAY) and statements are correct against
    an actual Postgres instance.

    Note: on a persistent DB already at head, this is a no-op exit-0 and
    catches little on its own — see test_migration_creates_all_expected_tables
    below for a schema-content assertion that gives signal regardless of DB
    state.
    """
    result = subprocess.run(
        ["poetry", "run", "alembic", "upgrade", "head"],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr


def test_migration_creates_all_expected_tables(engine: Engine):
    """The schema materialized from Base.metadata must include all 7 tables.

    Uses the session-scoped `engine` fixture from tests/conftest.py, which
    runs Base.metadata.create_all() against the cofoundaz_test DB — so this
    fails if any model/table is missing, independent of whether the dev DB
    (used by test_alembic_upgrade_head_runs above) is already at head.
    """
    tables = set(inspect(engine).get_table_names())
    expected = {
        "users",
        "user_profiles",
        "startups",
        "startup_profiles",
        "memberships",
        "jobs",
        "audit_log",
    }
    assert expected <= tables
