"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-08-12 18:14:05.998488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('on_behalf_of_user_id', sa.UUID(), nullable=True),
    sa.Column('startup_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before_hash', sa.String(length=64), nullable=True),
    sa.Column('after_hash', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_actor_created', 'audit_log', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('ix_audit_log_startup_created', 'audit_log', ['startup_id', 'created_at'], unique=False)
    op.create_table('jobs',
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='jobstatus', native_enum=False, length=20), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending_verification', 'active', 'locked', 'disabled', name='userstatus', native_enum=False, length=30), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_type', sa.Enum('none', 'totp', 'sms', name='mfatype', native_enum=False, length=10), nullable=False),
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('mfa_enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('startups',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('business_model', sa.Enum('b2b', 'b2c', 'b2b2c', 'marketplace', 'hardware', 'services', name='businessmodel', native_enum=False, length=20), nullable=True),
    sa.Column('stage', sa.Enum('idea', 'validation', 'build', 'launch', 'growth', 'scale', name='startupstage', native_enum=False, length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_startups_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_startups'))
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('how_heard', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_profiles'))
    )
    op.create_table('memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('founder', 'team_member', 'mentor', 'accountant', 'legal_advisor', 'business_consultant', 'investor', name='membershiprole', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'removed', name='membershipstatus', native_enum=False, length=20), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_memberships_invited_by_users')),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_memberships_startup_id_startups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('user_id', 'startup_id', name='uq_memberships_user_id_startup_id')
    )
    op.create_index('ix_memberships_startup_id', 'memberships', ['startup_id'], unique=False)
    op.create_table('startup_profiles',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('goals', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('onboarding_step', sa.Integer(), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_startup_profiles_startup_id_startups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('startup_id', name=op.f('pk_startup_profiles'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('startup_profiles')
    op.drop_index('ix_memberships_startup_id', table_name='memberships')
    op.drop_table('memberships')
    op.drop_table('user_profiles')
    op.drop_table('startups')
    op.drop_table('users')
    op.drop_table('jobs')
    op.drop_index('ix_audit_log_startup_created', table_name='audit_log')
    op.drop_index('ix_audit_log_actor_created', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
