"""onboarding

Revision ID: 0003_onboarding
Revises: 0002_auth_tables
Create Date: 2026-08-15 10:00:57.528459

Onboarding schema (Task 1: commit a569938; Task 2 SDD plan
.superpowers/sdd/2026-08-15-onboarding):
  - CREATE TABLE invitations (+ ix_invitations_email, ix_invitations_startup_id,
    uq_invitations_token_hash). New table, no lock on existing tables.
  - ADD COLUMN startup_profiles.assessment_pending boolean NOT NULL
    server_default true. Postgres 11+ adds a NOT NULL column with a constant
    server_default as a metadata-only change (no table rewrite, no
    AccessExclusiveLock hold beyond the instant catalog update) — safe as a
    single step even on a populated table.
  - ALTER COLUMN startups.name DROP NOT NULL. Metadata-only, near-instant
    regardless of table size.
  Estimated lock duration on prod-sized data: sub-second for all three ops
  (no rows to rewrite; dev DB currently has 0 rows in both tables). Verified
  via EXPLAIN-equivalent reasoning per Postgres docs, not measured against a
  populated clone (none exists yet for this pre-launch table).

  downgrade() note: `ALTER COLUMN startups.name SET NOT NULL` is only safe to
  reverse if no NULL names were written while nullable was in effect. If any
  startup row has NULL name at downgrade time, the downgrade will fail with a
  constraint violation — this is intentional (surfaces the data problem rather
  than silently truncating rows) and is not a bug in this migration.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0003_onboarding'
down_revision = '0002_auth_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('role', sa.Enum('founder', 'team_member', 'mentor', 'accountant', 'legal_advisor', 'business_consultant', 'investor', name='membershiprole', native_enum=False, length=30), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'expired', 'revoked', name='invitationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_user_id'], ['users.id'], name=op.f('fk_invitations_accepted_user_id_users')),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_invitations_invited_by_users')),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_invitations_startup_id_startups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invitations_token_hash'))
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_startup_id'), 'invitations', ['startup_id'], unique=False)
    op.add_column('startup_profiles', sa.Column('assessment_pending', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('startups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('startups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('startup_profiles', 'assessment_pending')
    op.drop_index(op.f('ix_invitations_startup_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
