"""assessment

Revision ID: 0004_assessment
Revises: 0003_onboarding
Create Date: 2026-08-17 12:41:03.801865

Assessment schema (Task 1: commit 20fb79a; Task 2 SDD plan
.superpowers/sdd/2026-08-16-assessment):
  - CREATE TABLE assessments (+ ix_assessments_startup_id,
    uq_assessments_startup_in_progress). The latter is a PARTIAL unique index
    — UNIQUE(startup_id) WHERE status = 'in_progress' — so a startup may have
    at most one in-progress assessment at a time, while completed/abandoned
    assessments for the same startup are unrestricted. Without the WHERE
    clause this would wrongly forbid a startup from ever starting a new
    assessment once it has one completed one on file.
  - CREATE TABLE assessment_answers (+ ix_assessment_answers_assessment_id,
    uq_answer_assessment_question UNIQUE(assessment_id, question_key)) — one
    answer per question per assessment.
  - CREATE TABLE assessment_results (assessment_id PK/FK to assessments.id,
    1:1 with assessments; no separate identity column).
  All three are new tables — this migration takes no lock on any existing
  table and holds no lock visible to concurrent readers/writers of
  assessments/startups/users; new-table CREATE TABLE/CREATE INDEX (including
  the partial index — the table is empty at creation time so a plain,
  non-CONCURRENTLY CREATE INDEX is safe and instant) is metadata-only from
  the perspective of every other table in the schema. Estimated lock
  duration on prod-sized data: sub-second (no existing rows anywhere in this
  migration's scope).

  Known gap (not fixed here — would require a Task-1 model change, out of
  this migration's one-concern scope): `assessments.created_by` (FK ->
  users.id) has no supporting index. A user delete/audit query filtering by
  created_by would seq-scan assessments. Flagged for a follow-up migration,
  not added speculatively here — adding an index unbacked by the SQLAlchemy
  model would make the next `alembic revision --autogenerate` immediately
  propose dropping it (schema drift).

  downgrade() drops all three tables in FK-safe order (assessment_results,
  assessment_answers, then assessments) and is lossy: any assessment data
  written while this migration was applied is destroyed on downgrade. That
  is inherent to dropping brand-new tables, not something to work around.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0004_assessment'
down_revision = '0003_onboarding'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('initial', 'quarterly', name='assessmenttype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='assessmentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('bank_version', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_assessments_created_by_users')),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_assessments_startup_id_startups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments'))
    )
    op.create_index(op.f('ix_assessments_startup_id'), 'assessments', ['startup_id'], unique=False)
    op.create_index('uq_assessments_startup_in_progress', 'assessments', ['startup_id'], unique=True, postgresql_where=sa.text("status = 'in_progress'"))
    op.create_table('assessment_answers',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('question_key', sa.String(length=80), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_answers_assessment_id_assessments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_answers')),
    sa.UniqueConstraint('assessment_id', 'question_key', name='uq_answer_assessment_question')
    )
    op.create_index(op.f('ix_assessment_answers_assessment_id'), 'assessment_answers', ['assessment_id'], unique=False)
    op.create_table('assessment_results',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('dimension_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_provisional', sa.Integer(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_results_assessment_id_assessments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id', name=op.f('pk_assessment_results'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_results')
    op.drop_index(op.f('ix_assessment_answers_assessment_id'), table_name='assessment_answers')
    op.drop_table('assessment_answers')
    op.drop_index('uq_assessments_startup_in_progress', table_name='assessments', postgresql_where=sa.text("status = 'in_progress'"))
    op.drop_index(op.f('ix_assessments_startup_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
