"""health score

Revision ID: 0005_health_score
Revises: 0004_assessment
Create Date: 2026-08-19

Module 06 (Health Score) schema (Task 1: app/db/models/health_score.py;
Task 2 SDD plan .superpowers/sdd/2026-08-19-health-score). Four new tables —
no lock on any existing table:
  - health_scores (+ ix_health_scores_startup_id UNIQUE) — one live score per
    startup.
  - health_score_history (+ ix_health_score_history_startup_id,
    ix_health_history_startup_created composite on (startup_id, created_at))
    — append-only trend ledger.
  - health_signals (+ ix_health_signals_startup_id) — current-state
    projection, replaced each recompute.
  - health_recommendations (+ ix_health_recommendations_startup_id,
    uq_recommendation_startup_key UNIQUE on (startup_id, key)) — dedupe
    identity per startup/recommendation-key.
  All FKs (startup_id -> startups.id) are ondelete="CASCADE". All four
  tables are brand new — this migration takes no lock on any existing table
  and holds no lock visible to concurrent readers/writers of startups; new
  table CREATE TABLE/CREATE INDEX (including the two UNIQUE indexes — each
  table is empty at creation time so a plain, non-CONCURRENTLY CREATE INDEX
  is safe and instant) is metadata-only from the perspective of every other
  table in the schema. Estimated lock duration on prod-sized data: sub-second
  (no existing rows anywhere in this migration's scope).

  This file was produced via `alembic revision --autogenerate` against the
  Task 1 ORM models (app/db/models/health_score.py) so the DDL is generated
  directly from, and verified against, those models — guaranteeing schema
  parity between the Alembic-built (E2E) and metadata.create_all-built
  (unit-test) schemas. Only the revision id, down_revision, and this
  docstring were hand-edited; the upgrade()/downgrade() bodies are as
  generated.

  downgrade() drops all four tables (order does not matter for FK safety —
  none of the four reference each other, only startups) and is lossy: any
  health-score data written while this migration was applied is destroyed
  on downgrade. That is inherent to dropping brand-new tables, not something
  to work around.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0005_health_score'
down_revision = '0004_assessment'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_recommendations',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('estimated_lift', sa.Integer(), nullable=False),
    sa.Column('effort', sa.Enum('low', 'medium', 'high', name='recommendationeffort', native_enum=False, length=10), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'dismissed', name='recommendationstatus', native_enum=False, length=12), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_health_recommendations_startup_id_startups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_recommendations'))
    )
    op.create_index(op.f('ix_health_recommendations_startup_id'), 'health_recommendations', ['startup_id'], unique=False)
    op.create_index('uq_recommendation_startup_key', 'health_recommendations', ['startup_id', 'key'], unique=True)
    op.create_table('health_score_history',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('dimension_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_health_score_history_startup_id_startups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_score_history'))
    )
    op.create_index('ix_health_history_startup_created', 'health_score_history', ['startup_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_health_score_history_startup_id'), 'health_score_history', ['startup_id'], unique=False)
    op.create_table('health_scores',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(length=20), nullable=False),
    sa.Column('dimension_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_health_scores_startup_id_startups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_scores'))
    )
    op.create_index(op.f('ix_health_scores_startup_id'), 'health_scores', ['startup_id'], unique=True)
    op.create_table('health_signals',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('contribution', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('source_ref', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_health_signals_startup_id_startups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_signals'))
    )
    op.create_index(op.f('ix_health_signals_startup_id'), 'health_signals', ['startup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_signals_startup_id'), table_name='health_signals')
    op.drop_table('health_signals')
    op.drop_index(op.f('ix_health_scores_startup_id'), table_name='health_scores')
    op.drop_table('health_scores')
    op.drop_index(op.f('ix_health_score_history_startup_id'), table_name='health_score_history')
    op.drop_index('ix_health_history_startup_created', table_name='health_score_history')
    op.drop_table('health_score_history')
    op.drop_index('uq_recommendation_startup_key', table_name='health_recommendations')
    op.drop_index(op.f('ix_health_recommendations_startup_id'), table_name='health_recommendations')
    op.drop_table('health_recommendations')
    # ### end Alembic commands ###
