"""roadmap

Revision ID: 0006_roadmap
Revises: 0005_health_score
Create Date: 2026-08-21

Module 05 (Roadmap Slice 1) schema (Task 1: app/db/models/roadmap.py; Task 2
SDD plan .superpowers/sdd/2026-08-21-roadmap-core). Five new tables — no
lock on any existing table:
  - roadmaps (+ ix_roadmaps_startup_id UNIQUE) — one roadmap per startup.
  - roadmap_phases (+ ix_roadmap_phases_roadmap_id) — ordered phases within
    a roadmap.
  - roadmap_milestones (+ ix_roadmap_milestones_phase_id) — milestones
    within a phase; owner_id is an optional FK to users.id (no ondelete —
    a deleted user does not cascade-delete milestone history, the FK just
    blocks the user delete until reassigned/nulled by the app).
  - roadmap_tasks (+ ix_roadmap_tasks_milestone_id) — tasks within a
    milestone; assignee_id is the same optional, non-cascading FK to
    users.id.
  - roadmap_task_dependencies — composite PK (task_id, depends_on_task_id),
    both FK to roadmap_tasks.id ON DELETE CASCADE, plus a CHECK constraint
    (task_id <> depends_on_task_id) preventing a task from depending on
    itself. The model names this check "ck_task_dep_not_self"; because
    CheckConstraint names are run through the naming_convention's "ck"
    template even when given explicitly (unlike Index/UniqueConstraint,
    which use an explicit name verbatim), the constraint's real name in
    Postgres is "ck_roadmap_task_dependencies_ck_task_dep_not_self" — this
    migration uses that computed name so it stays in parity with the ORM
    metadata (autogenerate would otherwise propose renaming it on the next
    run). No index is added on roadmap_task_dependencies beyond the
    composite PK: the PK already covers task_id as its leading column for
    forward-dependency lookups; a reverse lookup (dependents of a task) is
    left for a future migration if that query pattern shows up, per the
    one-concern-per-migration rule — speculative indexing here would be
    unbacked by any known query.

  All five tables are brand new — this migration takes no lock on any
  existing table (roadmap_milestones/roadmap_tasks add FKs to the existing
  users table, but adding a new FK to an existing table only requires a
  brief AccessShareLock/RowShareLock on users to validate — not an
  AccessExclusiveLock on users itself, since users is not being altered)
  and holds no lock visible to concurrent readers/writers of
  startups/users; new-table CREATE TABLE/CREATE INDEX (each table is empty
  at creation time so a plain, non-CONCURRENTLY CREATE INDEX, including the
  UNIQUE index on roadmaps.startup_id, is safe and instant) is metadata-only
  from the perspective of every other table in the schema. Estimated lock
  duration on prod-sized data: sub-second (no existing rows anywhere in
  this migration's scope; roadmaps/roadmap_phases/etc. do not exist yet).

  This file was produced via `alembic revision --autogenerate` against the
  Task 1 ORM models (app/db/models/roadmap.py) so the DDL is generated
  directly from, and verified against, those models — guaranteeing schema
  parity between the Alembic-built (E2E) and metadata.create_all-built
  (unit-test) schemas. Autogenerate emitted no noise against pre-existing
  tables this run (no server_default/CHECK-only diffs to strip, unlike the
  0004/0005 precedent) — only the revision id, down_revision, Create Date,
  and this docstring were hand-edited; the upgrade()/downgrade() bodies are
  exactly as generated.

  downgrade() drops all five tables in reverse FK-dependency order
  (roadmap_task_dependencies, roadmap_tasks, roadmap_milestones,
  roadmap_phases, roadmaps) and is lossy: any roadmap data written while
  this migration was applied is destroyed on downgrade. That is inherent to
  dropping brand-new tables, not something to work around.
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0006_roadmap"
down_revision = "0005_health_score"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roadmaps",
        sa.Column("startup_id", sa.UUID(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "idea",
                "validation",
                "build",
                "launch",
                "growth",
                "scale",
                name="startupstage",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("template_key", sa.String(length=60), nullable=False),
        sa.Column("template_version", sa.Integer(), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["startup_id"],
            ["startups.id"],
            name=op.f("fk_roadmaps_startup_id_startups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roadmaps")),
    )
    op.create_index(op.f("ix_roadmaps_startup_id"), "roadmaps", ["startup_id"], unique=True)
    op.create_table(
        "roadmap_phases",
        sa.Column("roadmap_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["roadmap_id"],
            ["roadmaps.id"],
            name=op.f("fk_roadmap_phases_roadmap_id_roadmaps"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roadmap_phases")),
    )
    op.create_index(
        op.f("ix_roadmap_phases_roadmap_id"), "roadmap_phases", ["roadmap_id"], unique=False
    )
    op.create_table(
        "roadmap_milestones",
        sa.Column("phase_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("due_on", sa.Date(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "todo", "in_progress", "done", name="roadmapstatus", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_roadmap_milestones_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["phase_id"],
            ["roadmap_phases.id"],
            name=op.f("fk_roadmap_milestones_phase_id_roadmap_phases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roadmap_milestones")),
    )
    op.create_index(
        op.f("ix_roadmap_milestones_phase_id"), "roadmap_milestones", ["phase_id"], unique=False
    )
    op.create_table(
        "roadmap_tasks",
        sa.Column("milestone_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "effort",
            sa.Enum("small", "medium", "large", name="taskeffort", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "todo", "in_progress", "done", name="roadmapstatus", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column("due_on", sa.Date(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"], ["users.id"], name=op.f("fk_roadmap_tasks_assignee_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["milestone_id"],
            ["roadmap_milestones.id"],
            name=op.f("fk_roadmap_tasks_milestone_id_roadmap_milestones"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roadmap_tasks")),
    )
    op.create_index(
        op.f("ix_roadmap_tasks_milestone_id"), "roadmap_tasks", ["milestone_id"], unique=False
    )
    op.create_table(
        "roadmap_task_dependencies",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("depends_on_task_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "task_id <> depends_on_task_id",
            name=op.f("ck_roadmap_task_dependencies_ck_task_dep_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["depends_on_task_id"],
            ["roadmap_tasks.id"],
            name=op.f("fk_roadmap_task_dependencies_depends_on_task_id_roadmap_tasks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["roadmap_tasks.id"],
            name=op.f("fk_roadmap_task_dependencies_task_id_roadmap_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "task_id", "depends_on_task_id", name=op.f("pk_roadmap_task_dependencies")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roadmap_task_dependencies")
    op.drop_index(op.f("ix_roadmap_tasks_milestone_id"), table_name="roadmap_tasks")
    op.drop_table("roadmap_tasks")
    op.drop_index(op.f("ix_roadmap_milestones_phase_id"), table_name="roadmap_milestones")
    op.drop_table("roadmap_milestones")
    op.drop_index(op.f("ix_roadmap_phases_roadmap_id"), table_name="roadmap_phases")
    op.drop_table("roadmap_phases")
    op.drop_index(op.f("ix_roadmaps_startup_id"), table_name="roadmaps")
    op.drop_table("roadmaps")
    # ### end Alembic commands ###
