"""roadmap applied templates

Revision ID: 0007_roadmap_applied_templates
Revises: 0006_roadmap
Create Date: 2026-08-22

Module 05 (Roadmap Slice 2) schema (Task 1: app/db/models/roadmap.py; Task 1
SDD plan .superpowers/sdd/2026-08-22-roadmap-deps-templates). Adds one
column to the existing `roadmaps` table:
  - `applied_template_keys` (JSONB, NOT NULL, server_default '[]') — tracks
    which supplemental templates (e.g. "mvp-build") have been layered onto
    this roadmap's base stage template, so re-application is idempotent.

This is `ADD COLUMN ... NOT NULL` with a constant default on an existing
table. Postgres 11+ (this project targets 17) does not rewrite the table
for a constant DEFAULT on ADD COLUMN — the default is stored in the
catalog and applied lazily on read for pre-existing rows, so this does not
require the ADD-nullable/backfill/SET-NOT-NULL three-step split that a
non-constant or backfill-dependent default would need. `roadmaps` is a new,
low-row-count table as of migration 0006 (one row per startup with a
generated roadmap) — even without the PG11+ optimization this would be a
sub-millisecond rewrite. Lock: `ACCESS EXCLUSIVE` on `roadmaps` only, for
the metadata-only catalog update — no data rewrite, no lock on any other
table. Estimated lock duration on prod-sized data: sub-second.

This file was produced via `alembic revision --autogenerate` against the
Task 1 ORM model change (app/db/models/roadmap.py) so the DDL is generated
directly from, and verified against, that model. Only the revision id,
down_revision, and this docstring were hand-edited; the upgrade()/
downgrade() bodies are as generated, with no unrelated autogen noise.

downgrade() drops the column and is lossy: any data written to
`applied_template_keys` while this migration was applied is destroyed on
downgrade. That is inherent to dropping a column, not something to work
around.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0007_roadmap_applied_templates'
down_revision = '0006_roadmap'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('applied_template_keys', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmaps', 'applied_template_keys')
    # ### end Alembic commands ###
