"""roadmap replan

Revision ID: 0008_roadmap_replan
Revises: 0007_roadmap_applied_templates
Create Date: 2026-08-27

Module 05 (Roadmap Slice 3, AI Re-plan) schema (Task 1: app/db/models/roadmap.py;
Task 1 SDD plan .superpowers/sdd/2026-08-26-roadmap-replan). Two changes:

  - New table `roadmap_replans` — one row per applied re-plan operation on a
    roadmap: `roadmap_id` (FK -> roadmaps.id, CASCADE, indexed), `applied_by`
    (FK -> users.id, NOT NULL), `change_count` (Integer), `changes` (JSONB,
    the list of per-milestone diffs), `summary` (String(200)). This is a new,
    empty table — `CREATE TABLE` + one index, no lock contention with
    existing data.
  - Two nullable columns added to the existing `roadmap_milestones` table:
    `last_replanned_at` (timestamptz, null) and `last_replan_reason`
    (String(300), null). Both are `ADD COLUMN ... NULL` with no default, so
    Postgres performs a metadata-only catalog update — no table rewrite, no
    backfill needed.

Lock: `ACCESS EXCLUSIVE` on `roadmap_milestones` for the two nullable
column adds (metadata-only, no rewrite) and on the new `roadmap_replans`
table for its own creation (irrelevant to concurrent readers/writers of
other tables). Estimated lock duration on prod-sized data: sub-second for
both — `roadmap_milestones` is a low-row-count table (per-startup roadmap
milestones) and nullable-column adds without a default never rewrite.

This file was produced via `alembic revision --autogenerate` against the
Task 1 ORM model change (app/db/models/roadmap.py) so the DDL is generated
directly from, and verified against, that model. Only the revision id,
down_revision, and this docstring were hand-edited; the upgrade()/
downgrade() bodies are as generated, with no unrelated autogen noise.

downgrade() drops the two `roadmap_milestones` columns and the
`roadmap_replans` table entirely — this is lossy: any re-plan history
(the `roadmap_replans` rows) and any milestone re-plan markers written
while this migration was applied are destroyed on downgrade. That is
inherent to dropping a table/columns, not something to work around; there
is no meaningful "undo" for re-plan audit history once policy is to remove
the schema that stores it.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0008_roadmap_replan'
down_revision = '0007_roadmap_applied_templates'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_replans',
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('applied_by', sa.UUID(), nullable=False),
    sa.Column('change_count', sa.Integer(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], name=op.f('fk_roadmap_replans_applied_by_users')),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], name=op.f('fk_roadmap_replans_roadmap_id_roadmaps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_replans'))
    )
    op.create_index(op.f('ix_roadmap_replans_roadmap_id'), 'roadmap_replans', ['roadmap_id'], unique=False)
    op.add_column('roadmap_milestones', sa.Column('last_replanned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('roadmap_milestones', sa.Column('last_replan_reason', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmap_milestones', 'last_replan_reason')
    op.drop_column('roadmap_milestones', 'last_replanned_at')
    op.drop_index(op.f('ix_roadmap_replans_roadmap_id'), table_name='roadmap_replans')
    op.drop_table('roadmap_replans')
    # ### end Alembic commands ###
