"""mission

Revision ID: 0009_mission
Revises: 0007_roadmap_applied_templates
Create Date: 2026-08-27

Module 04 (Today's Mission) schema (Task 1: app/db/models/mission.py; SDD
plan .superpowers/sdd/2026-08-26-todays-mission). Three brand new tables —
no lock on any existing table:
  - missions (+ ix_missions_startup_id, + UNIQUE uq_mission_startup_date on
    (startup_id, mission_date)) — one mission per startup per day.
  - mission_tasks (+ ix_mission_tasks_mission_id) — the tasks generated into
    a mission. `roadmap_task_id` is a bare UUID column with NO foreign key —
    a deliberate soft link back to roadmap_tasks.id so a mission snapshot
    survives independently of that roadmap task being edited/regenerated/
    deleted later; enforcing referential integrity here is not desired.
  - mission_settings (PK = startup_id, FK to startups.id ON DELETE CASCADE)
    — one row per startup holding mission-generation preferences
    (mission_size, delivery_time, weekend_missions).

This revision chains off 0008_roadmap_replan. It and 0008 were authored in
parallel as siblings off 0007 (each in its own worktree); at merge time
(Roadmap Slice 3 / PR #16 landed first) 0009's down_revision was repointed
from 0007 to 0008 so the history is a linear 0007 → 0008 → 0009 with a
single head, rather than two branches off 0007.

All three tables are brand new — this migration takes no lock on any
existing table (missions/mission_settings add FKs to the existing startups
table, but adding a new FK to an existing table only requires a brief
AccessShareLock/RowShareLock on startups to validate — not an
AccessExclusiveLock on startups itself, since startups is not being
altered). Every CREATE TABLE/CREATE INDEX here is metadata-only from the
perspective of every other table in the schema (each new table is empty at
creation time, so a plain, non-CONCURRENTLY CREATE INDEX is safe and
instant). Estimated lock duration on prod-sized data: sub-second (no
existing rows anywhere in this migration's scope).

This file was produced via `alembic revision --autogenerate` against the
Task 1 ORM models (app/db/models/mission.py) so the DDL is generated
directly from, and verified against, those models — guaranteeing schema
parity between the Alembic-built (E2E) and metadata.create_all-built
(unit-test) schemas. Autogenerate emitted no noise against pre-existing
tables this run — only the revision id, down_revision, Create Date,
formatting, and this docstring were hand-edited; the upgrade()/downgrade()
bodies are exactly as generated (reordered to declare `missions` before
`mission_tasks` for readability — same statements, no behavior change).

downgrade() drops all three tables in reverse FK-dependency order
(mission_tasks, missions, mission_settings) and is lossy: any mission data
written while this migration was applied is destroyed on downgrade. That is
inherent to dropping brand-new tables, not something to work around.
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0009_mission"
down_revision = "0008_roadmap_replan"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "missions",
        sa.Column("startup_id", sa.UUID(), nullable=False),
        sa.Column("mission_date", sa.Date(), nullable=False),
        sa.Column("generated_by", sa.String(length=10), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "complete", name="missionstatus", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["startup_id"],
            ["startups.id"],
            name=op.f("fk_missions_startup_id_startups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_missions")),
        sa.UniqueConstraint("startup_id", "mission_date", name="uq_mission_startup_date"),
    )
    op.create_index(op.f("ix_missions_startup_id"), "missions", ["startup_id"], unique=False)
    op.create_table(
        "mission_tasks",
        sa.Column("mission_id", sa.UUID(), nullable=False),
        sa.Column("roadmap_task_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=True),
        sa.Column(
            "effort",
            sa.Enum("small", "medium", "large", name="taskeffort", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "todo",
                "done",
                "snoozed",
                "rejected",
                name="missiontaskstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reject_reason", sa.String(length=60), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
            name=op.f("fk_mission_tasks_mission_id_missions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mission_tasks")),
    )
    op.create_index(
        op.f("ix_mission_tasks_mission_id"), "mission_tasks", ["mission_id"], unique=False
    )
    op.create_table(
        "mission_settings",
        sa.Column("startup_id", sa.UUID(), nullable=False),
        sa.Column("mission_size", sa.Integer(), nullable=False),
        sa.Column("delivery_time", sa.Time(), nullable=False),
        sa.Column("weekend_missions", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["startup_id"],
            ["startups.id"],
            name=op.f("fk_mission_settings_startup_id_startups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("startup_id", name=op.f("pk_mission_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mission_settings")
    op.drop_index(op.f("ix_mission_tasks_mission_id"), table_name="mission_tasks")
    op.drop_table("mission_tasks")
    op.drop_index(op.f("ix_missions_startup_id"), table_name="missions")
    op.drop_table("missions")
    # ### end Alembic commands ###
