"""dashboard

Revision ID: 0010_dashboard
Revises: 0009_mission
Create Date: 2026-08-31

Module 02 (Founder Dashboard) schema (Task 1: app/db/models/activity.py; SDD
plan .superpowers/sdd/2026-08-31-dashboard). One brand new table — no lock
on any existing table:
  - activity_log (+ composite ix_activity_log_startup_created on
    (startup_id, created_at, id)) — the append-only feed of founder-visible
    events (task completions, mission generation, roadmap replans, etc.)
    that the dashboard reads from. `entity_id` is a bare UUID column with
    NO foreign key — a deliberate soft cross-module reference (mirrors
    mission_tasks.roadmap_task_id) so a log row survives independently of
    whatever entity it references being edited/regenerated/deleted later;
    enforcing referential integrity here is not desired.

This revision chains directly off 0009_mission, the current alembic head.

activity_log is brand new — this migration takes no lock on any existing
table (it adds FKs to the existing startups and users tables, but adding a
new FK to an existing table only requires a brief AccessShareLock/
RowShareLock to validate — not an AccessExclusiveLock on those tables,
since neither is being altered). The CREATE TABLE/CREATE INDEX here are
metadata-only from the perspective of every other table in the schema
(the new table is empty at creation time, so a plain, non-CONCURRENTLY
CREATE INDEX is safe and instant). Estimated lock duration on prod-sized
data: sub-second (no existing rows anywhere in this migration's scope).

This file was produced via `alembic revision --autogenerate` against the
Task 1 ORM model (app/db/models/activity.py) so the DDL is generated
directly from, and verified against, that model — guaranteeing schema
parity between the Alembic-built (E2E) and metadata.create_all-built
(unit-test) schemas. Autogenerate emitted no noise against pre-existing
tables this run — only the revision id, down_revision, Create Date, and
this docstring were hand-edited; the upgrade()/downgrade() bodies are
exactly as generated.

downgrade() drops the index then the table and is lossy: any activity
written while this migration was applied is destroyed on downgrade. That is
inherent to dropping a brand-new table, not something to work around.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0010_dashboard"
down_revision = "0009_mission"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_log",
        sa.Column("startup_id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("summary", sa.String(length=300), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_activity_log_actor_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["startup_id"],
            ["startups.id"],
            name=op.f("fk_activity_log_startup_id_startups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_log")),
    )
    op.create_index(
        "ix_activity_log_startup_created",
        "activity_log",
        ["startup_id", "created_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_activity_log_startup_created", table_name="activity_log")
    op.drop_table("activity_log")
    # ### end Alembic commands ###
