"""business_canvases

Revision ID: 0011_business_canvases
Revises: 0010_dashboard
Create Date: 2026-09-01

Module 08 (Business Builder) schema (Slice 1 Task 1:
app/db/models/business.py; SDD plan
.superpowers/sdd/2026-09-01-business-builder-canvas). One brand new table —
no lock on any existing table:
  - business_canvases (+ UNIQUE uq_business_canvas_startup_type on
    (startup_id, type)) — one canvas row per startup per CanvasType
    (business_model / lean / value_prop / mission_vision / swot). `blocks`
    is JSONB holding the block scaffold from
    app.services.business.canvas_defs.empty_blocks(); `version` is a plain
    optimistic-lock counter (server_default "1") checked by later tasks in
    this slice and surfaced via CanvasVersionConflict on mismatch.

`type` follows the same VARCHAR-backed enum convention as every other
StrEnum column in this codebase (see missions.status, mission_tasks.effort,
etc. in 0009_mission.py): `native_enum=False` — no Postgres CREATE TYPE/DROP
TYPE, just a plain VARCHAR(20) with a CHECK-free application-level enum.
downgrade() therefore only needs to drop the table; there is no enum type to
drop.

This revision chains directly off 0010_dashboard, the current alembic head.

business_canvases is brand new — this migration takes no lock on any
existing table (it adds a FK to the existing startups table, but adding a
new FK to an existing table only requires a brief AccessShareLock/
RowShareLock to validate — not an AccessExclusiveLock on startups, since
startups is not being altered). The CREATE TABLE here is metadata-only from
the perspective of every other table in the schema (the new table is empty
at creation time). Estimated lock duration on prod-sized data: sub-second
(no existing rows anywhere in this migration's scope).

This file was produced via `alembic revision --autogenerate` against the
Task 1 ORM model (app/db/models/business.py) so the DDL is generated
directly from, and verified against, that model — guaranteeing schema
parity between the Alembic-built (E2E) and metadata.create_all-built
(unit-test) schemas. Autogenerate emitted no noise against pre-existing
tables this run — only the revision id, down_revision, Create Date,
formatting, and this docstring were hand-edited; the upgrade()/downgrade()
bodies are exactly as generated.

downgrade() drops the table and is lossy: any canvas data written while this
migration was applied is destroyed on downgrade. That is inherent to
dropping a brand-new table, not something to work around.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0011_business_canvases"
down_revision = "0010_dashboard"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_canvases",
        sa.Column("startup_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "business_model",
                "lean",
                "value_prop",
                "mission_vision",
                "swot",
                name="canvastype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("blocks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["startup_id"],
            ["startups.id"],
            name=op.f("fk_business_canvases_startup_id_startups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_canvases")),
        sa.UniqueConstraint("startup_id", "type", name="uq_business_canvas_startup_type"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("business_canvases")
    # ### end Alembic commands ###
