"""business_records

Revision ID: 0012_business_records
Revises: 0011_business_canvases
Create Date: 2026-09-04

Module 08 (Business Builder) schema (Slice 2 Task 1:
app/db/models/business.py; SDD plan
.superpowers/sdd/2026-09-04-business-builder-records). One brand new table —
no lock on any existing table:
  - business_records (+ ix_business_records_startup_id, + composite
    ix_business_records_startup_kind on (startup_id, kind, position)) — one
    row per typed artifact (persona / revenue_stream / competitor /
    pricing) that a startup has added under Business Builder. `kind` is the
    RecordKind discriminator; `data` is JSONB validated against the
    matching Pydantic schema in app.services.business.record_defs
    (RECORD_SCHEMAS) before write; `position` orders records of the same
    kind for a startup (drag-reorder in the FE). The standalone
    `startup_id` index is kept alongside the composite index (even though
    startup_id is the composite's leading column) to match this codebase's
    convention of always giving an FK column its own index — see
    ix_business_canvases_startup_id in 0011_business_canvases.py and
    ix_memberships_startup_id in 0001_initial_schema.py.

`kind` follows the same VARCHAR-backed enum convention as every other
StrEnum column in this codebase (see business_canvases.type in
0011_business_canvases.py, missions.status in 0009_mission.py, etc.):
`native_enum=False` — no Postgres CREATE TYPE/DROP TYPE, just a plain
VARCHAR(20) with a CHECK-free application-level enum. downgrade() therefore
only needs to drop the table; there is no enum type to drop.

This revision chains directly off 0011_business_canvases, the current
alembic head.

business_records is brand new — this migration takes no lock on any
existing table (it adds a FK to the existing startups table, but adding a
new FK to an existing table only requires a brief AccessShareLock/
RowShareLock to validate — not an AccessExclusiveLock on startups, since
startups is not being altered). The CREATE TABLE here is metadata-only from
the perspective of every other table in the schema (the new table is empty
at creation time). Estimated lock duration on prod-sized data: sub-second
(no existing rows anywhere in this migration's scope).

This file was produced via `alembic revision --autogenerate` against the
Task 1 ORM model (app/db/models/business.py) so the DDL is generated
directly from, and verified against, that model — guaranteeing schema
parity between the Alembic-built (E2E) and metadata.create_all-built
(unit-test) schemas. Autogenerate emitted no noise against pre-existing
tables this run — only the revision id, down_revision, Create Date,
formatting, and this docstring were hand-edited; the upgrade()/downgrade()
bodies are exactly as generated.

downgrade() drops the table and is lossy: any record data written while
this migration was applied is destroyed on downgrade. That is inherent to
dropping a brand-new table, not something to work around.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0012_business_records"
down_revision = "0011_business_canvases"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_records",
        sa.Column("startup_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "persona",
                "revenue_stream",
                "competitor",
                "pricing",
                name="recordkind",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["startup_id"],
            ["startups.id"],
            name=op.f("fk_business_records_startup_id_startups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_records")),
    )
    op.create_index(
        op.f("ix_business_records_startup_id"),
        "business_records",
        ["startup_id"],
        unique=False,
    )
    op.create_index(
        "ix_business_records_startup_kind",
        "business_records",
        ["startup_id", "kind", "position"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_business_records_startup_kind", table_name="business_records")
    op.drop_index(op.f("ix_business_records_startup_id"), table_name="business_records")
    op.drop_table("business_records")
    # ### end Alembic commands ###
