"""business_suggestions

Revision ID: 0013_business_suggestions
Revises: 0012_business_records
Create Date: 2026-09-08

Module 08 (Business Builder) schema (Slice 3 Task 1:
app/db/models/business.py; SDD plan
.superpowers/sdd/2026-09-08-business-builder-suggestions). One brand new
table — no lock on any existing table:
  - business_suggestions (+ ix_business_suggestions_startup_id,
    + ix_business_suggestions_author_id, + composite
    ix_business_suggestions_startup_status on (startup_id, status)) — one
    row per business-consultant suggestion made against a startup's
    Business Builder data (a canvas block update or a record
    create/update/delete). `op` is the SuggestionOp discriminator
    (canvas_update / record_create / record_update / record_delete);
    `target` (JSONB) identifies what the suggestion applies to (canvas type
    or record id/kind); `payload` (JSONB, nullable) carries the proposed
    change; `base_version` (nullable Integer) pins the canvas version the
    suggestion was drafted against for optimistic-concurrency conflict
    detection at apply time; `note` is the consultant's free-text
    rationale; `status` is the SuggestionStatus lifecycle (pending /
    approved / rejected), defaulting to `pending` at the DB level via
    `server_default`; `resolved_by_id`/`resolved_at` record who resolved
    the suggestion and when (both nullable — unset while pending).
    `resolved_by_id` uses `ondelete="SET NULL"` (unlike `author_id`/
    `startup_id`, which cascade-delete) so that deleting the resolving
    user does not destroy suggestion history, only its resolver
    attribution. Both `startup_id` and `author_id` get their own
    standalone index in addition to the composite `startup_id`/`status`
    index, matching this codebase's convention of always giving an FK
    column its own index — see ix_business_records_startup_id in
    0012_business_records.py and ix_memberships_startup_id in
    0001_initial_schema.py.

`op` and `status` follow the same VARCHAR-backed enum convention as every
other StrEnum column in this codebase (see business_records.kind in
0012_business_records.py, missions.status in 0009_mission.py, etc.):
`native_enum=False` — no Postgres CREATE TYPE/DROP TYPE, just a plain
VARCHAR(20) with a CHECK-free application-level enum. downgrade() therefore
only needs to drop indexes and the table; there is no enum type to drop.

This revision chains directly off 0012_business_records, the current
alembic head (confirmed via `poetry run alembic heads` at spec time — the
journal PR #37 introducing `0013_journal` had not merged, so this branch
does not need to rebase and claims the `0013_` slot).

business_suggestions is brand new — this migration takes no lock on any
existing table (it adds FKs to the existing startups/users tables, but
adding a new FK to an existing table only requires a brief AccessShareLock/
RowShareLock to validate — not an AccessExclusiveLock on startups or users,
since neither is being altered). The CREATE TABLE here is metadata-only
from the perspective of every other table in the schema (the new table is
empty at creation time). Estimated lock duration on prod-sized data:
sub-second (no existing rows anywhere in this migration's scope).

This file was produced via `alembic revision --autogenerate` against the
Task 1 ORM model (app/db/models/business.py) so the DDL is generated
directly from, and verified against, that model — guaranteeing schema
parity between the Alembic-built (E2E) and metadata.create_all-built
(unit-test) schemas. Autogenerate emitted no noise against pre-existing
tables this run — only the revision id, down_revision, Create Date,
formatting, and this docstring were hand-edited; the upgrade()/downgrade()
bodies are exactly as generated (split out of a single autogenerate run
that also detected business_positioning_maps, which was moved verbatim
into the following revision, 0014_business_positioning_maps, so each
revision creates exactly one table).

downgrade() drops the table and is lossy: any suggestion data written while
this migration was applied is destroyed on downgrade. That is inherent to
dropping a brand-new table, not something to work around.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0013_business_suggestions"
down_revision = "0012_business_records"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_suggestions",
        sa.Column("startup_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column(
            "op",
            sa.Enum(
                "canvas_update",
                "record_create",
                "record_update",
                "record_delete",
                name="suggestionop",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("target", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("base_version", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                name="suggestionstatus",
                native_enum=False,
                length=20,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("resolved_by_id", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_business_suggestions_author_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"],
            ["users.id"],
            name=op.f("fk_business_suggestions_resolved_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["startup_id"],
            ["startups.id"],
            name=op.f("fk_business_suggestions_startup_id_startups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_suggestions")),
    )
    op.create_index(
        op.f("ix_business_suggestions_author_id"),
        "business_suggestions",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_business_suggestions_startup_id"),
        "business_suggestions",
        ["startup_id"],
        unique=False,
    )
    op.create_index(
        "ix_business_suggestions_startup_status",
        "business_suggestions",
        ["startup_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_business_suggestions_startup_status", table_name="business_suggestions")
    op.drop_index(op.f("ix_business_suggestions_startup_id"), table_name="business_suggestions")
    op.drop_index(op.f("ix_business_suggestions_author_id"), table_name="business_suggestions")
    op.drop_table("business_suggestions")
    # ### end Alembic commands ###
