"""business_positioning_maps

Revision ID: 0014_business_positioning_maps
Revises: 0013_business_suggestions
Create Date: 2026-09-08

Module 08 (Business Builder) schema (Slice 3 Task 1:
app/db/models/business.py; SDD plan
.superpowers/sdd/2026-09-08-business-builder-suggestions). One brand new
table — no lock on any existing table:
  - business_positioning_maps (+ ix_business_positioning_maps_startup_id,
    + uq_business_positioning_map_startup) — at most one competitor
    positioning map per startup (`startup_id` is both indexed for FK lookup
    and unique-constrained, since a startup has exactly zero or one map).
    `axes` (JSONB) holds the map's axis definitions (e.g. `{"x": {"label":
    "Price"}, "y": {"label": ...}}`); the coordinate/point data itself is
    deferred to a later task per the Slice 3 plan (it needs no migration —
    see the plan's Task 5) and is not part of this table's schema. The
    standalone `startup_id` index is kept alongside the unique constraint
    (a unique constraint on Postgres already implies a unique index, but
    this codebase's convention — see ix_business_records_startup_id in
    0012_business_records.py — is to always give an FK column its own
    named index for FK-lookup clarity; autogenerate independently detected
    and emitted both here) to match the FK-index convention used
    throughout this codebase.

This revision chains directly off 0013_business_suggestions (this same
Slice 3 Task 1 unit), which chains off 0012_business_records, the alembic
head at spec time.

business_positioning_maps is brand new — this migration takes no lock on
any existing table (it adds an FK to the existing startups table, but
adding a new FK to an existing table only requires a brief AccessShareLock/
RowShareLock to validate — not an AccessExclusiveLock on startups, since
startups is not being altered). The CREATE TABLE here is metadata-only
from the perspective of every other table in the schema (the new table is
empty at creation time). Estimated lock duration on prod-sized data:
sub-second (no existing rows anywhere in this migration's scope).

This file was produced via `alembic revision --autogenerate` against the
Task 1 ORM model (app/db/models/business.py) so the DDL is generated
directly from, and verified against, that model — guaranteeing schema
parity between the Alembic-built (E2E) and metadata.create_all-built
(unit-test) schemas. Autogenerate emitted no noise against pre-existing
tables this run — only the revision id, down_revision, Create Date,
formatting, and this docstring were hand-edited; the upgrade()/downgrade()
bodies are exactly as generated (split out of a single autogenerate run
that also detected business_suggestions, which was moved verbatim into the
preceding revision, 0013_business_suggestions, so each revision creates
exactly one table).

downgrade() drops the table and is lossy: any positioning-map data written
while this migration was applied is destroyed on downgrade. That is
inherent to dropping a brand-new table, not something to work around.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0014_business_positioning_maps"
down_revision = "0013_business_suggestions"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_positioning_maps",
        sa.Column("startup_id", sa.UUID(), nullable=False),
        sa.Column(
            "axes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                '\'{"x": {"label": "Price", "low": "Low", "high": "High"}, '
                '"y": {"label": "Quality", "low": "Low", "high": "High"}}\'::jsonb'
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["startup_id"],
            ["startups.id"],
            name=op.f("fk_business_positioning_maps_startup_id_startups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_positioning_maps")),
        sa.UniqueConstraint("startup_id", name="uq_business_positioning_map_startup"),
    )
    op.create_index(
        op.f("ix_business_positioning_maps_startup_id"),
        "business_positioning_maps",
        ["startup_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_business_positioning_maps_startup_id"), table_name="business_positioning_maps"
    )
    op.drop_table("business_positioning_maps")
    # ### end Alembic commands ###
