"""documents

Revision ID: 0016_documents
Revises: 0015_business_positioning_maps
Create Date: 2026-09-09

Module 18 (Documents & Templates) schema (Slice 1 Task 1:
app/db/models/document.py; SDD plan
.superpowers/sdd/2026-09-09-documents-templates-slice1). One brand new
table — no lock on any existing table:
  - documents (+ ix_documents_startup_id, + ix_documents_created_by_id,
    + composite ix_documents_startup_kind on (startup_id, kind)) — one row
    per structured document (title + ordered markdown `sections`) that a
    startup has under Documents & Templates. `kind` is the DocumentKind
    discriminator (business_plan/pitch_deck/financial_model/meeting_notes/
    one_pager/custom); `status` is DocumentStatus (draft/final);
    `sections` is JSONB holding the ordered list of {id, heading, body}
    blocks (canvas pattern, same shape as BusinessCanvas.blocks in
    0011_business_canvases.py). The standalone `startup_id` index is kept
    alongside the composite index to match this codebase's convention of
    always giving an FK column its own index — see
    ix_business_records_startup_id in 0012_business_records.py and
    ix_memberships_startup_id in 0001_initial_schema.py. `created_by_id`
    is nullable with ON DELETE SET NULL (the document survives its
    author's account being removed).

`kind` and `status` follow the same VARCHAR-backed enum convention as
every other StrEnum column in this codebase (see business_records.kind in
0012_business_records.py, missions.status in 0009_mission.py, etc.):
`native_enum=False` — no Postgres CREATE TYPE/DROP TYPE, just a plain
VARCHAR(20) with a CHECK-free application-level enum. downgrade() therefore
only needs to drop the table; there is no enum type to drop.

This revision chains directly off 0015_business_positioning_maps, the
current alembic head.

documents is brand new — this migration takes no lock on any existing
table (it adds FKs to the existing startups and users tables, but adding a
new FK to an existing table only requires a brief AccessShareLock/
RowShareLock to validate — not an AccessExclusiveLock on startups or
users, since neither is being altered). The CREATE TABLE here is
metadata-only from the perspective of every other table in the schema (the
new table is empty at creation time). Estimated lock duration on
prod-sized data: sub-second (no existing rows anywhere in this migration's
scope).

This file was produced via `alembic revision --autogenerate` against the
Task 1 ORM model (app/db/models/document.py) so the DDL is generated
directly from, and verified against, that model — guaranteeing schema
parity between the Alembic-built (E2E) and metadata.create_all-built
(unit-test) schemas. Autogenerate emitted no noise against pre-existing
tables this run — only the revision id, down_revision, Create Date,
formatting, and this docstring were hand-edited; the upgrade()/downgrade()
bodies are exactly as generated.

downgrade() drops the table and is lossy: any document data written while
this migration was applied is destroyed on downgrade. That is inherent to
dropping a brand-new table, not something to work around.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0016_documents"
down_revision = "0015_business_positioning_maps"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("startup_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "business_plan",
                "pitch_deck",
                "financial_model",
                "meeting_notes",
                "one_pager",
                "custom",
                name="documentkind",
                native_enum=False,
                length=20,
            ),
            server_default="custom",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("draft", "final", name="documentstatus", native_enum=False, length=20),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("ai_generated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("folder", sa.String(length=120), nullable=True),
        sa.Column("template_key", sa.String(length=50), nullable=True),
        sa.Column("title", sa.String(length=200), server_default="", nullable=False),
        sa.Column(
            "sections", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_documents_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["startup_id"],
            ["startups.id"],
            name=op.f("fk_documents_startup_id_startups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(
        op.f("ix_documents_created_by_id"), "documents", ["created_by_id"], unique=False
    )
    op.create_index(op.f("ix_documents_startup_id"), "documents", ["startup_id"], unique=False)
    op.create_index("ix_documents_startup_kind", "documents", ["startup_id", "kind"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_documents_startup_kind", table_name="documents")
    op.drop_index(op.f("ix_documents_startup_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_created_by_id"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
