"""document_files

Revision ID: 0017_document_files
Revises: 0016_documents
Create Date: 2026-09-10

Module 18 (Documents & Templates) schema (Slice 2 Task 2:
app/db/models/document.py; SDD plan
.superpowers/sdd/2026-09-10-documents-files-slice2). One brand new table —
no lock on any existing table:
  - document_files (+ ix_document_files_startup_id,
    + ix_document_files_uploaded_by_id, + composite
    ix_document_files_startup_folder on (startup_id, folder)) — one row per
    opaque uploaded file (Cloudinary-backed, per Slice 2 Task 1's
    CloudinaryStorage) attached to a startup's Documents & Templates
    workspace. `storage_key` is the backend-opaque key used to address the
    object in the configured Storage implementation (delete/lookup); `url`
    is the public/delivery URL returned by that backend at upload time. The
    standalone `startup_id` index is kept alongside the composite index to
    match this codebase's convention of always giving an FK column its own
    index — see ix_documents_startup_id in 0016_documents.py and
    ix_business_records_startup_id in 0012_business_records.py.
    `uploaded_by_id` is nullable with ON DELETE SET NULL (the file survives
    its uploader's account being removed); `folder` is a free-text label
    (nullable — files need not be foldered), matching documents.folder in
    0016_documents.py.

This revision chains directly off 0016_documents, the current alembic
head.

document_files is brand new — this migration takes no lock on any existing
table (it adds FKs to the existing startups and users tables, but adding a
new FK to an existing table only requires a brief AccessShareLock/
RowShareLock to validate — not an AccessExclusiveLock on startups or
users, since neither is being altered). The CREATE TABLE here is
metadata-only from the perspective of every other table in the schema (the
new table is empty at creation time). Estimated lock duration on
prod-sized data: sub-second (no existing rows anywhere in this migration's
scope).

This file was produced via `alembic revision --autogenerate` against the
Task 2 ORM model (app/db/models/document.py) so the DDL is generated
directly from, and verified against, that model — guaranteeing schema
parity between the Alembic-built (E2E) and metadata.create_all-built
(unit-test) schemas. Autogenerate emitted no noise against pre-existing
tables this run — only the revision id, down_revision, Create Date,
formatting, and this docstring were hand-edited; the upgrade()/downgrade()
bodies are exactly as generated.

downgrade() drops the table and is lossy: any document_files data written
while this migration was applied is destroyed on downgrade. That is
inherent to dropping a brand-new table, not something to work around.
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0017_document_files"
down_revision = "0016_documents"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_files",
        sa.Column("startup_id", sa.UUID(), nullable=False),
        sa.Column("uploaded_by_id", sa.UUID(), nullable=True),
        sa.Column("folder", sa.String(length=120), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["startup_id"],
            ["startups.id"],
            name=op.f("fk_document_files_startup_id_startups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_document_files_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_files")),
    )
    op.create_index(
        "ix_document_files_startup_folder", "document_files", ["startup_id", "folder"], unique=False
    )
    op.create_index(
        op.f("ix_document_files_startup_id"), "document_files", ["startup_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_files_uploaded_by_id"), "document_files", ["uploaded_by_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_files_uploaded_by_id"), table_name="document_files")
    op.drop_index(op.f("ix_document_files_startup_id"), table_name="document_files")
    op.drop_index("ix_document_files_startup_folder", table_name="document_files")
    op.drop_table("document_files")
    # ### end Alembic commands ###
