"""document_shares

Revision ID: 0018_document_shares
Revises: 0017_document_files
Create Date: 2026-09-12

Module 18 (Documents & Templates) schema (Slice 3 Task 1:
app/db/models/document.py; SDD plan
.superpowers/sdd/2026-09-12-documents-sharing-slice3). One brand new table —
no lock on any existing table:
  - document_shares (+ ix_document_shares_startup_id,
    + ix_document_shares_document_id, + ix_document_shares_shared_by_id,
    + composite ix_document_shares_startup_created on
    (startup_id, created_at)) — one row per external share link issued
    against a startup's document (email + hashed access token +
    view/comment access level). The standalone FK-column indexes are kept
    alongside the composite index to match this codebase's convention of
    always giving an FK column its own index — see
    ix_document_files_startup_id in 0017_document_files.py and
    ix_documents_startup_id in 0016_documents.py. `shared_by_id` is
    nullable with ON DELETE SET NULL (the share survives the sharing user's
    account being removed, mirroring uploaded_by_id in
    0017_document_files.py); `token_hash` carries a unique constraint/index
    since it is the only credential used to resolve a share externally —
    only the SHA-256 hash of the raw token is stored, never the token
    itself. `expires_at`, `revoked_at`, and `last_viewed_at` are nullable
    timestamps tracking the share's lifecycle.

This revision chains directly off 0017_document_files, the current
alembic head.

document_shares is brand new — this migration takes no lock on any
existing table (it adds FKs to the existing startups, documents, and
users tables, but adding a new FK to an existing table only requires a
brief AccessShareLock/RowShareLock to validate — not an
AccessExclusiveLock on startups, documents, or users, since none of them
is being altered). The CREATE TABLE here is metadata-only from the
perspective of every other table in the schema (the new table is empty
at creation time). Estimated lock duration on prod-sized data: sub-second
(no existing rows anywhere in this migration's scope).

This file was produced via `alembic revision --autogenerate` against the
Task 1 ORM model (app/db/models/document.py) so the DDL is generated
directly from, and verified against, that model — guaranteeing schema
parity between the Alembic-built (E2E) and metadata.create_all-built
(unit-test) schemas. Autogenerate emitted no noise against pre-existing
tables this run — only the revision id, down_revision, Create Date,
formatting, and this docstring were hand-edited; the upgrade()/downgrade()
bodies are exactly as generated.

downgrade() drops the table and is lossy: any document_shares data
written while this migration was applied is destroyed on downgrade. That
is inherent to dropping a brand-new table, not something to work around.
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0018_document_shares"
down_revision = "0017_document_files"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_shares",
        sa.Column("startup_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("shared_by_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "access_level",
            sa.Enum("view", "comment", name="shareaccess", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_viewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_shares_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shared_by_id"],
            ["users.id"],
            name=op.f("fk_document_shares_shared_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["startup_id"],
            ["startups.id"],
            name=op.f("fk_document_shares_startup_id_startups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_shares")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_document_shares_token_hash")),
    )
    op.create_index(
        op.f("ix_document_shares_document_id"), "document_shares", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_shares_shared_by_id"), "document_shares", ["shared_by_id"], unique=False
    )
    op.create_index(
        "ix_document_shares_startup_created",
        "document_shares",
        ["startup_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_shares_startup_id"), "document_shares", ["startup_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_shares_startup_id"), table_name="document_shares")
    op.drop_index("ix_document_shares_startup_created", table_name="document_shares")
    op.drop_index(op.f("ix_document_shares_shared_by_id"), table_name="document_shares")
    op.drop_index(op.f("ix_document_shares_document_id"), table_name="document_shares")
    op.drop_table("document_shares")
    # ### end Alembic commands ###
