"""learning

Revision ID: 0019_learning
Revises: 0020_signatures
Create Date: 2026-09-14

Module 17 (Learning Academy) schema (Task 1: app/db/models/learning.py;
plan docs/superpowers/plans/2026-09-11-learning-academy.md). Three brand new
tables — no lock on any existing table:
  - enrollments (+ ix_enrollments_startup_id, + ix_enrollments_user_id) —
    one row per member per course per workspace
    (uq_enrollments_startup_user_course), holding a progress percentage
    kept between 0 and 100 (ck_enrollments_progress_range) and completed_at.
  - lesson_progress (+ ix_lesson_progress_startup_id,
    + ix_lesson_progress_user_id) — one row per completed lesson per member
    per workspace (uq_lesson_progress_startup_user_lesson).
  - certificates (+ ix_certificates_startup_id, + ix_certificates_user_id)
    — one certificate per member per course per workspace
    (uq_certificates_startup_user_course), identified by a unique
    credential_code (uq_certificates_credential_code).
course_id and lesson_id are text keys into the in-code catalog
(app/services/learning/catalog.py), not foreign keys — the catalog is not
stored in the database yet (spec decision D1).

This revision chains off 0020_signatures (Module 18 Slice 4), which merged
into develop first. 0019 was reserved for Module 17 (issue #52 heads-up), so
the chain runs 0018_document_shares -> 0020_signatures -> 0019_learning.

All three tables are brand new, so this migration takes no lock on any
existing table beyond the brief lock needed to validate the new foreign
keys to startups and users. Estimated lock duration on prod-sized data:
sub-second.

This file was produced via `alembic revision --autogenerate` against
app/db/models/learning.py. Only the revision id, down_revision, Create Date
and this docstring were hand-edited; the upgrade()/downgrade() bodies are
exactly as generated.

downgrade() drops the three tables and is lossy: any enrolments, lesson
progress and certificates written while this migration was applied are
destroyed on downgrade.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0019_learning"
down_revision = '0020_signatures'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.Text(), nullable=False),
    sa.Column('credential_code', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_certificates_startup_id_startups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_certificates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates')),
    sa.UniqueConstraint('credential_code', name=op.f('uq_certificates_credential_code')),
    sa.UniqueConstraint('startup_id', 'user_id', 'course_id', name='uq_certificates_startup_user_course')
    )
    op.create_index(op.f('ix_certificates_startup_id'), 'certificates', ['startup_id'], unique=False)
    op.create_index(op.f('ix_certificates_user_id'), 'certificates', ['user_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.Text(), nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('progress BETWEEN 0 AND 100', name=op.f('ck_enrollments_progress_range')),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_enrollments_startup_id_startups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_enrollments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('startup_id', 'user_id', 'course_id', name='uq_enrollments_startup_user_course')
    )
    op.create_index(op.f('ix_enrollments_startup_id'), 'enrollments', ['startup_id'], unique=False)
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.Text(), nullable=False),
    sa.Column('lesson_id', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_lesson_progress_startup_id_startups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lesson_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_progress')),
    sa.UniqueConstraint('startup_id', 'user_id', 'lesson_id', name='uq_lesson_progress_startup_user_lesson')
    )
    op.create_index(op.f('ix_lesson_progress_startup_id'), 'lesson_progress', ['startup_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_user_id'), 'lesson_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_progress_user_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_startup_id'), table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('ix_enrollments_user_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_startup_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_certificates_user_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_startup_id'), table_name='certificates')
    op.drop_table('certificates')
    # ### end Alembic commands ###
