"""signatures

Revision ID: 0020_signatures
Revises: 0018_document_shares
Create Date: 2026-09-14

Module 18 (Documents & Templates) schema (Slice 4 Task 1:
app/db/models/document.py; SDD plan
.superpowers/sdd/2026-09-14-documents-esignature-slice4). Two brand new
tables — no lock on any existing table:
  - signature_requests (+ ix_signature_requests_startup_id,
    + ix_signature_requests_file_id, + ix_signature_requests_created_by_id,
    + composite ix_signature_requests_startup_created on
    (startup_id, created_at)) — one row per e-signature request raised
    against a startup's uploaded file (title + lifecycle status +
    expiry/completion/cancellation timestamps).
  - signature_signers (+ ix_signature_signers_request_id, +
    unique/indexed token_hash) — one row per signer on a signature
    request (email + hashed signing token + ordered position + signed
    audit fields). The standalone FK-column indexes are kept alongside
    the composite index to match this codebase's convention of always
    giving an FK column its own index — see
    ix_document_shares_startup_id in 0018_document_shares.py.
    `created_by_id` on signature_requests is nullable with ON DELETE SET
    NULL (the request survives the creating user's account being
    removed, mirroring shared_by_id in 0018_document_shares.py);
    `token_hash` on signature_signers carries a unique constraint/index
    since it is the only credential used to resolve a signer's link
    externally — only the SHA-256 hash of the raw token is stored, never
    the token itself.

This revision chains directly off 0018_document_shares, the current
alembic head (0019 is reserved for Module 17 per the #52 heads-up and is
intentionally skipped).

Both tables are brand new — this migration takes no lock on any existing
table (it adds FKs to the existing startups, document_files, and users
tables, plus signature_requests itself for signature_signers, but adding
a new FK to an existing table only requires a brief
AccessShareLock/RowShareLock to validate — not an AccessExclusiveLock on
startups, document_files, or users, since none of them is being
altered). The CREATE TABLE statements here are metadata-only from the
perspective of every other table in the schema (both new tables are
empty at creation time). Estimated lock duration on prod-sized data:
sub-second (no existing rows anywhere in this migration's scope).

This file was produced via `alembic revision --autogenerate` against the
Task 1 ORM models (app/db/models/document.py) so the DDL is generated
directly from, and verified against, those models — guaranteeing schema
parity between the Alembic-built (E2E) and metadata.create_all-built
(unit-test) schemas. Autogenerate emitted no noise against pre-existing
tables this run — only the revision id, down_revision, Create Date,
formatting, and this docstring were hand-edited; the upgrade()/
downgrade() bodies are exactly as generated.

downgrade() drops both tables and is lossy: any signature_requests /
signature_signers data written while this migration was applied is
destroyed on downgrade. That is inherent to dropping brand-new tables,
not something to work around.
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0020_signatures"
down_revision = "0018_document_shares"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signature_requests",
        sa.Column("startup_id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "awaiting",
                "complete",
                "cancelled",
                name="signaturerequeststatus",
                native_enum=False,
                length=20,
            ),
            server_default="awaiting",
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_signature_requests_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["document_files.id"],
            name=op.f("fk_signature_requests_file_id_document_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["startup_id"],
            ["startups.id"],
            name=op.f("fk_signature_requests_startup_id_startups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signature_requests")),
    )
    op.create_index(
        op.f("ix_signature_requests_created_by_id"),
        "signature_requests",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_signature_requests_file_id"), "signature_requests", ["file_id"], unique=False
    )
    op.create_index(
        "ix_signature_requests_startup_created",
        "signature_requests",
        ["startup_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_signature_requests_startup_id"),
        "signature_requests",
        ["startup_id"],
        unique=False,
    )
    op.create_table(
        "signature_signers",
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("signed_name", sa.String(length=255), nullable=True),
        sa.Column("signed_ip", sa.String(length=64), nullable=True),
        sa.Column("signed_user_agent", sa.String(length=512), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["signature_requests.id"],
            name=op.f("fk_signature_signers_request_id_signature_requests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signature_signers")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_signature_signers_token_hash")),
    )
    op.create_index(
        op.f("ix_signature_signers_request_id"), "signature_signers", ["request_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signature_signers_request_id"), table_name="signature_signers")
    op.drop_table("signature_signers")
    op.drop_index(op.f("ix_signature_requests_startup_id"), table_name="signature_requests")
    op.drop_index("ix_signature_requests_startup_created", table_name="signature_requests")
    op.drop_index(op.f("ix_signature_requests_file_id"), table_name="signature_requests")
    op.drop_index(op.f("ix_signature_requests_created_by_id"), table_name="signature_requests")
    op.drop_table("signature_requests")
    # ### end Alembic commands ###
