"""notifications

Revision ID: 0021_notifications
Revises: 0020_signatures
Create Date: 2026-09-14 15:57:13.816057

Module 20 (Notifications) Slice 1 schema (Task 2: app/db/models/notification.py;
SDD plan .superpowers/sdd/2026-09-14-notifications-feed-slice1). One brand new
table — no lock on any existing table: notifications (+ ix_notifications_user_id,
+ ix_notifications_startup_id, + composite ix_notifications_user_startup_created
on (user_id, startup_id, created_at)) — one row per in-app notification fanned
out to a user within a startup. Both FK columns (user_id, startup_id) keep their
own standalone index alongside the composite, matching this codebase's
convention of always giving an FK column its own index — see
ix_signature_requests_startup_id in 0020_signatures.py. Both FKs are ON DELETE
CASCADE (a notification has no meaning once its user or startup is gone).
`body` defaults to '' and `data` defaults to '{}' so callers can omit either
when they have no free-text body or structured payload to attach.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0021_notifications'
down_revision = '0020_signatures'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=500), server_default='', nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_notifications_startup_id_startups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_startup_id'), 'notifications', ['startup_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_startup_created', 'notifications', ['user_id', 'startup_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_startup_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_startup_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
