"""notifications email: preferences + jobs worker columns

Revision ID: 0022_notifications_email
Revises: 0021_notifications
Create Date: 2026-09-15 13:28:57.396774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0022_notifications_email'
down_revision = '0021_notifications'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('master_email', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_notification_preferences_startup_id_startups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences')),
    sa.UniqueConstraint('user_id', 'startup_id', name='uq_notification_preferences_user_startup')
    )
    op.create_index(op.f('ix_notification_preferences_startup_id'), 'notification_preferences', ['startup_id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.add_column('jobs', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('jobs', sa.Column('run_after', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'run_after')
    op.drop_column('jobs', 'attempts')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_startup_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
