"""scheduled_runs ledger

Revision ID: 0024_scheduled_runs
Revises: 0023_learning
Create Date: 2026-09-18 22:18:26.389939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0024_scheduled_runs'
down_revision = '0023_learning'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_runs',
    sa.Column('task_key', sa.String(length=60), nullable=False),
    sa.Column('scope_key', sa.String(length=64), nullable=False),
    sa.Column('period_key', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_runs')),
    sa.UniqueConstraint('task_key', 'scope_key', 'period_key', name='uq_scheduled_runs_task_scope_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_runs')
    # ### end Alembic commands ###
