"""business_plans

Revision ID: 0026_business_plans
Revises: 0025_roadmap_milestone_due_idx
Create Date: 2026-09-19

§08.11 (AI Business Plan Generator) schema (Task 1:
app/db/models/business.py; SDD plan
.superpowers/sdd/2026-09-19-ai-business-plan-generator). One brand new
table — no lock on any existing table:
  - business_plans (+ ix_business_plans_document_id,
    + ix_business_plans_startup_id) — one row per AI business-plan
    generation run for a startup. `status` is BusinessPlanStatus
    (generating/complete/failed), tracking the async LLM job that produces
    the plan. `document_id` points at the resulting `documents` row once
    generation completes and is nullable (null while `generating`, and
    ON DELETE SET NULL so the run row survives the document being deleted);
    `created_by_id` is the user who triggered the run. The standalone
    `startup_id` index is kept to match this codebase's convention of
    always giving an FK column its own index — see ix_documents_startup_id
    in 0016_documents.py and ix_business_canvases_startup_id in
    0011_business_canvases.py.

`status` follows the same VARCHAR-backed enum convention as every other
StrEnum column in this codebase (see documents.kind/status in
0016_documents.py, business_canvases.type in 0011_business_canvases.py,
etc.): `native_enum=False` — no Postgres CREATE TYPE/DROP TYPE, just a
plain VARCHAR(20) with a CHECK-free application-level enum. downgrade()
therefore only needs to drop the table; there is no enum type to drop.

This revision chains directly off 0025_roadmap_milestone_due_idx, the
current alembic head.

business_plans is brand new — this migration takes no lock on any
existing table (it adds FKs to the existing startups, documents, and
users tables, but adding a new FK to an existing table only requires a
brief AccessShareLock/RowShareLock to validate — not an
AccessExclusiveLock on startups, documents, or users, since none of them
is being altered). The CREATE TABLE here is metadata-only from the
perspective of every other table in the schema (the new table is empty at
creation time). Estimated lock duration on prod-sized data: sub-second (no
existing rows anywhere in this migration's scope).

This file was produced via `alembic revision --autogenerate` against the
Task 1 ORM model (app/db/models/business.py) so the DDL is generated
directly from, and verified against, that model — guaranteeing schema
parity between the Alembic-built (E2E) and metadata.create_all-built
(unit-test) schemas. Autogenerate emitted no noise against pre-existing
tables this run — only the revision id, down_revision, Create Date,
formatting, and this docstring were hand-edited; the upgrade()/downgrade()
bodies are exactly as generated.

downgrade() drops the table and is lossy: any business-plan run data
written while this migration was applied is destroyed on downgrade. That
is inherent to dropping a brand-new table, not something to work around.
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0026_business_plans"
down_revision = "0025_roadmap_milestone_due_idx"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_plans",
        sa.Column("startup_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "generating",
                "complete",
                "failed",
                name="businessplanstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_business_plans_created_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_business_plans_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["startup_id"],
            ["startups.id"],
            name=op.f("fk_business_plans_startup_id_startups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_plans")),
    )
    op.create_index(
        op.f("ix_business_plans_document_id"), "business_plans", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_business_plans_startup_id"), "business_plans", ["startup_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_business_plans_startup_id"), table_name="business_plans")
    op.drop_index(op.f("ix_business_plans_document_id"), table_name="business_plans")
    op.drop_table("business_plans")
    # ### end Alembic commands ###
