"""daily_briefings

Revision ID: 0027_daily_briefings
Revises: 0026_business_plans
Create Date: 2026-09-19

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0027_daily_briefings"
down_revision = "0026_business_plans"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_briefings",
        sa.Column("startup_id", sa.UUID(), nullable=False),
        sa.Column("briefing_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "generating", "ready", "failed", name="briefingstatus", native_enum=False, length=12
            ),
            nullable=False,
        ),
        sa.Column("briefing", sa.Text(), nullable=False),
        sa.Column("risks", sa.Text(), nullable=False),
        sa.Column("opportunities", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["startup_id"],
            ["startups.id"],
            name=op.f("fk_daily_briefings_startup_id_startups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_briefings")),
        sa.UniqueConstraint("startup_id", "briefing_date", name="uq_briefing_startup_date"),
    )
    op.create_index(
        op.f("ix_daily_briefings_startup_id"), "daily_briefings", ["startup_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_daily_briefings_startup_id"), table_name="daily_briefings")
    op.drop_table("daily_briefings")
    # ### end Alembic commands ###
