"""roadmap_replan_rationale

Revision ID: 0028_roadmap_replan_rationale
Revises: 0027_daily_briefings
Create Date: 2026-09-21

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0028_roadmap_replan_rationale"
down_revision = "0027_daily_briefings"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roadmap_replans", sa.Column("rationale", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roadmap_replans", "rationale")
    # ### end Alembic commands ###
