"""startup_profile_ai_panel

Revision ID: 0029_startup_profile_ai_panel
Revises: 0028_roadmap_replan_rationale
Create Date: 2026-09-21

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0029_startup_profile_ai_panel"
down_revision = "0028_roadmap_replan_rationale"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("startup_profiles", sa.Column("ai_panel", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("startup_profiles", "ai_panel")
    # ### end Alembic commands ###
