"""llm_usage_daily

Revision ID: 0030_llm_usage_daily
Revises: 0029_startup_profile_ai_panel
Create Date: 2026-09-21 14:48:53.722928

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0030_llm_usage_daily"
down_revision = "0029_startup_profile_ai_panel"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_usage_daily",
        sa.Column("startup_id", sa.UUID(), nullable=False),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["startup_id"],
            ["startups.id"],
            name=op.f("fk_llm_usage_daily_startup_id_startups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_usage_daily")),
        sa.UniqueConstraint("startup_id", "usage_date", name="uq_llm_usage_startup_date"),
    )
    op.create_index(
        op.f("ix_llm_usage_daily_startup_id"), "llm_usage_daily", ["startup_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_usage_daily_startup_id"), table_name="llm_usage_daily")
    op.drop_table("llm_usage_daily")
    # ### end Alembic commands ###
