"""learning_recommendations

Revision ID: 0031_learning_recommendations
Revises: 0030_llm_usage_daily
Create Date: 2026-09-23

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0031_learning_recommendations"
down_revision = "0030_llm_usage_daily"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_recommendations",
        sa.Column("startup_id", sa.UUID(), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=True),
        sa.Column("reason", sa.String(length=300), nullable=True),
        sa.Column(
            "status",
            sa.Enum("generating", "ready", native_enum=False, length=12),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["startup_id"],
            ["startups.id"],
            name=op.f("fk_learning_recommendations_startup_id_startups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_recommendations")),
        sa.UniqueConstraint("startup_id", name="uq_learning_reco_startup"),
    )
    op.create_index(
        op.f("ix_learning_recommendations_startup_id"),
        "learning_recommendations",
        ["startup_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_learning_recommendations_startup_id"), table_name="learning_recommendations"
    )
    op.drop_table("learning_recommendations")
    # ### end Alembic commands ###
