"""validation

Revision ID: 0035_validation
Revises: 0034_campaigns_segments
Create Date: 2026-09-24

Module 09 (Validation Hub) schema (Task 1: app/db/models/validation.py;
plan docs/superpowers/plans/2026-09-20-validation-hub.md). Five brand new
tables — no lock on any existing table:
  - assumptions (+ ix_assumptions_startup_id) — one row per belief being
    tested, with a risk level and a status that may move freely around the
    board (spec D8). evidence_count is derived on read, never stored (D2).
  - experiments (+ ix_experiments_startup_id) — a test and its numbers:
    free-form config and metrics as JSONB, plus the assumptions it bears on
    (assumption_ids, spec D9).
  - interviews (+ ix_interviews_startup_id) — who was interviewed, their
    segment, the notes, the key quotes and a verdict.
  - surveys (+ ix_surveys_startup_id, + uq_surveys_token_hash) — the question
    schema as JSONB, and the SHA-256 hash of the public token that addresses
    the survey publicly. Only the hash is stored; the raw token is returned
    once, when the survey is opened (spec section 4).
  - survey_responses (+ ix_survey_responses_startup_id,
    + ix_survey_responses_survey_id) — one anonymous answer set. There is
    deliberately no user_id: respondents are members of the public and nothing
    about them is recorded beyond submitted_at (spec D3). startup_id is copied
    from the survey so member reads stay workspace-scoped (D4).

This revision chains off 0034_campaigns_segments, the develop head when this branch
was last rebased. It has been renumbered twice (0026 -> 0034 -> 0035) as Modules 03,
08 and 10 merged ahead of it; the head is re-checked before pushing and renumbered
again if anything else lands first.

All five tables are brand new, so this migration takes no lock on any existing
table beyond the brief lock needed to validate the new foreign keys to startups
and surveys. Estimated lock duration on prod-sized data: sub-second.

This file was produced via `alembic revision --autogenerate` against
app/db/models/validation.py. Only the revision id, Create Date and this
docstring were hand-edited; the upgrade()/downgrade() bodies are exactly as
generated.

downgrade() drops the five tables and is lossy: every assumption, experiment,
interview, survey and response written while this migration was applied is
destroyed on downgrade.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0035_validation"
down_revision = '0034_campaigns_segments'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assumptions',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('risk', sa.Enum('low', 'medium', 'high', name='risklevel', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('untested', 'testing', 'validated', 'invalidated', name='assumptionstatus', native_enum=False, length=20), server_default='untested', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_assumptions_startup_id_startups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assumptions'))
    )
    op.create_index(op.f('ix_assumptions_startup_id'), 'assumptions', ['startup_id'], unique=False)
    op.create_table('experiments',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('smoke_test', 'landing_page', 'ad_test', 'other', name='experimenttype', native_enum=False, length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('draft', 'live', 'ended', name='experimentstatus', native_enum=False, length=20), server_default='draft', nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('assumption_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_experiments_startup_id_startups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index(op.f('ix_experiments_startup_id'), 'experiments', ['startup_id'], unique=False)
    op.create_table('interviews',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('interviewee', sa.String(length=255), nullable=False),
    sa.Column('segment', sa.String(length=120), nullable=True),
    sa.Column('held_on', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('key_quotes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('verdict', sa.Enum('supports', 'contradicts', 'neutral', name='interviewverdict', native_enum=False, length=20), nullable=False),
    sa.Column('assumption_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_interviews_startup_id_startups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviews'))
    )
    op.create_index(op.f('ix_interviews_startup_id'), 'interviews', ['startup_id'], unique=False)
    op.create_table('surveys',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.Enum('draft', 'open', 'closed', name='surveystatus', native_enum=False, length=20), server_default='draft', nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_surveys_startup_id_startups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_surveys')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_surveys_token_hash'))
    )
    op.create_index(op.f('ix_surveys_startup_id'), 'surveys', ['startup_id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('fk_survey_responses_startup_id_startups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_survey_responses_survey_id_surveys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_responses'))
    )
    op.create_index(op.f('ix_survey_responses_startup_id'), 'survey_responses', ['startup_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_survey_id'), 'survey_responses', ['survey_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_responses_survey_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_startup_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_surveys_startup_id'), table_name='surveys')
    op.drop_table('surveys')
    op.drop_index(op.f('ix_interviews_startup_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_experiments_startup_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_assumptions_startup_id'), table_name='assumptions')
    op.drop_table('assumptions')
    # ### end Alembic commands ###
