"""JWT issuance and password hashing primitives.

Password hashing calls the `bcrypt` package directly. It previously went through
passlib's `CryptContext(schemes=["bcrypt"])`, which had to go: passlib 1.7.4 is
the last release (October 2020, unmaintained) and its bcrypt backend cannot
initialise at all against bcrypt >= 5. passlib's one-time backend self-test
hashes a 255-byte secret to probe for the BSD wraparound bug
(`passlib/handlers/bcrypt.py`, `detect_wrap_bug`); bcrypt 5 raises `ValueError`
on any secret over 72 bytes instead of truncating, so the backend never loads
and EVERY call fails -- including one hashing a 5-character password.

The wire format is unchanged. passlib's CryptContext emitted standard `$2b$12$`
bcrypt hashes, which is exactly what `bcrypt.hashpw` + `bcrypt.gensalt(12)`
emits, so every hash already stored in `users.password_hash` keeps verifying.
That claim is not taken on trust -- `tests/core/test_password_hashing.py`
verifies 126 hashes generated by the real pre-migration passlib against this
module (see `tests/fixtures/passlib_golden_hashes.json`).

Future argon2 migration: bcrypt and argon2 hashes are self-identifying by prefix
(`$2a$`/`$2b$`/`$2y$` vs `$argon2id$`), so argon2 can be introduced later by
dispatching on that prefix in `verify_password` and rehashing on next successful
login. No data migration and no forced password reset is required for that step.
"""

from datetime import UTC, datetime, timedelta
from typing import Any, cast

import bcrypt
from jose import jwt
from loguru import logger

from app.core.config import settings

# bcrypt only ever consumes the first 72 bytes of a secret. This is a property of
# the algorithm, not of any particular library.
BCRYPT_MAX_PASSWORD_BYTES = 72

# passlib's CryptContext defaulted to cost 12, and every hash in the existing
# database was written at that cost. Pinned explicitly rather than relying on
# `bcrypt.gensalt()`'s default so a future bump in the bcrypt package cannot
# silently change the cost factor for new hashes.
_BCRYPT_ROUNDS = 12


def _prepare_secret(password: str) -> bytes:
    """Encode a password to the exact bytes bcrypt should consume.

    Truncation to 72 bytes is REQUIRED for backward compatibility, not a
    convenience. passlib truncated silently, so any user whose password exceeds
    72 bytes has a stored hash covering only the first 72. Passing the full
    secret to bcrypt 5 raises `ValueError`; passing it to bcrypt 4 would hash
    different input than passlib did. Either way that user could never log in
    again. Truncating here reproduces passlib's behaviour byte for byte.

    The cut is on the UTF-8 BYTES, never on characters. `password[:72]` is a
    different and wrong operation: "密" * 30 is 30 characters but 90 bytes, so
    character-slicing leaves an over-length secret and bcrypt 5 still raises.
    Byte-slicing can land mid-codepoint and produce invalid UTF-8, which is
    fine and intended -- bcrypt takes bytes, the result is never decoded, and
    it is precisely what passlib did.

    `hash` and `verify` both go through this one function so their preprocessing
    can never drift apart.
    """
    return password.encode("utf-8")[:BCRYPT_MAX_PASSWORD_BYTES]


def create_access_token(subject: str | Any, expires_delta: timedelta | None = None) -> str:
    if expires_delta:
        expire = datetime.now(UTC) + expires_delta
    else:
        expire = datetime.now(UTC) + timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)

    to_encode = {"exp": expire, "sub": str(subject)}
    encoded_jwt = jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM)
    return cast(str, encoded_jwt)


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """Check a password against a stored bcrypt hash.

    Returns False rather than raising when the stored hash is malformed. A hash
    that bcrypt cannot parse can never authenticate anyone, so False is the
    correct answer; letting the `ValueError` escape would turn one corrupt row
    into a 500 on the login path. The row is logged (without the hash or the
    password) so the corruption is still visible to ops.
    """
    try:
        return bcrypt.checkpw(_prepare_secret(plain_password), hashed_password.encode("utf-8"))
    except ValueError:
        logger.error("Malformed bcrypt hash encountered during password verification")
        return False


def get_password_hash(password: str) -> str:
    return bcrypt.hashpw(_prepare_secret(password), bcrypt.gensalt(rounds=_BCRYPT_ROUNDS)).decode(
        "ascii"
    )
